[project]
name = "sql-connector"
version = "0.1.0"
description = "Wrapper around SQLAlchemy to connect and execute queries against a MySQL database, supporting optional SSH tunnels and returning query results as pandas DataFrame"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.3.3",
    "paramiko<3",
    "pymysql>=1.1.2",
    "pyyaml>=6.0.3",
    "sqlalchemy>=2.0.44",
    "sshtunnel>=0.4.0",
]

[dependency-groups]
dev = [
    "debugpy>=1.8.17",
    "ruff>=0.14.4",
]
